<html>
<body>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Jensen</th>
      <td>-394.55</td>
    </tr>
    <tr>
      <th>Roy</th>
      <td>-341.1</td>
    </tr>
    <tr>
      <th>Samson</th>
      <td>-92.9671</td>
    </tr>
    <tr>
      <th>Sammy</th>
      <td>-52.3384</td>
    </tr>
    <tr>
      <th>Dickson</th>
      <td>-38</td>
    </tr>
    <tr>
      <th>Vian</th>
      <td>-3.81667</td>
    </tr>
    <tr>
      <th>Sammas</th>
      <td>37.6604</td>
    </tr>
    <tr>
      <th>Terry</th>
      <td>106.544</td>
    </tr>
    <tr>
      <th>Nathan</th>
      <td>173.483</td>
    </tr>
    <tr>
      <th>Lolo</th>
      <td>217.066</td>
    </tr>
    <tr>
      <th>Debby</th>
      <td>388.016</td>
    </tr>
  </tbody>
</table>
</body>
</html>
